[build-system]
# hatchling v1.27 was first version to use default metadata version 2.4, allowing project.license
# and project.license-files fields following PEP-639
requires = ["hatchling>=1.27", "hatch-vcs"]
build-backend = "hatchling.build"


[project]
name = "mini_afsd"
version = "1.2.1"
authors = [
  {name = "Ryan Gottwald"},
  {name = "Donald Erb", email = "derb15@vt.edu"},
]
maintainers = [
    {name = "Donald Erb", email = "derb15@vt.edu"},
]
description = "A program for controlling a miniturized additive friction stir deposition (AFSD) machine."
readme = "README.rst"
license-files = [
    "LICENSE.txt"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Physics",
]
keywords = [
    "AFSD",
    "additive friction stir deposition",
    "engineering",
    "additive manufacturing",
]
requires-python = ">=3.7"
dependencies = [
    "labjack-ljm",
    "numpy",
    "matplotlib>=3.4",
    "pyserial",
]

[project.urls]
Homepage = "https://github.com/RyTheGuy355/MiniAFSDCode"
Documentation = "https://mini_afsd.readthedocs.io"

[project.optional-dependencies]
release = [
    "build",
    "bump-my-version",
    "twine",
]

